name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Input prosledjen JS akciji
      - name: Log Greeting Time
        run: echo "pristupacemo promenljivoj koja je vracena iz greet koraka i izvrsene akcije ${{steps.greet.outputs.time}}"