name: CI

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        working-directory: ./workflow-app
        run: npm ci
      - name: Build App
        working-directory: ./workflow-app
        run: npm run build
      - name: Run Tests
        working-directory: ./workflow-app
        run: npm run test
        env:
          CI: true
